# Generated by Django 2.2.6 on 2019-11-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20191117_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.PositiveIntegerField(default=1.99),
        ),
    ]
